### ISSUE TITLE
Betaflight 10.8.0 APK outdated bug

### ISSUE THREAD

**Issue by TylerDD4** [betaflight/betaflight-configurator#2948]
### Describe the bug

After updating to the latest release of 10.8.0 APK it alerts that the Configurator is outdated and tells you how to update. Figured it's a bug, because it does it all the time. 

### To Reproduce

Open betaflight Configurator APK after downloading newest release. 

### Expected behavior

No error message about outdated firmware 

### Configurator version

10.8.0 5ec9465

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by TylerDD4** [comment]
![SmartSelect_20220614-101215_Betaflight Configurator (Debug Build)](https://user-images.githubusercontent.com/96781377/173614486-be522a30-12d6-4898-b350-cabf960b03ab.jpg)

**Comment by TylerDD4** [comment]
![Screenshot_20220614-101226_Betaflight Configurator (Debug Build)](https://user-images.githubusercontent.com/96781377/173614542-0eade2cd-d9b2-4dac-a04f-4e69266fc071.jpg)

**Comment by haslinghuis** [comment]
FIxed in https://github.com/betaflight/betaflight-configurator/pull/2942

**Comment by jawz101** [comment]
betaflight-configurator_10.8.0-debug-5ec9465_android.apk

Does this version have the fix?  Because I'm still getting the error on this one

**Comment by TylerDD4** [comment]
> betaflight-configurator_10.8.0-debug-5ec9465_android.apk
> 
> Does this version have the fix? Because I'm still getting the error on this one

Exactly... Replied as fixed, but the error hasn't gone away.

**Comment by jawz101** [comment]
The above dude posted a commit that changed the build ID for Betaflight from 10.8 to 10.9 so I have no idea how that means Android app's error goes away for v10.8.
